service: dnd_creator
image: ghcr.io/christianloring/dnd_creator

servers:
  web:
    hosts:
      - fablecodex.com

proxy:
  ssl: true
  host: fablecodex.com

# registry:
#   server: ghcr.io
#   username: christianloring
#   password:
#     - KAMAL_REGISTRY_PASSWORD

registry:
  server: ghcr.io
  username: christianloring
  password: <%= ENV["KAMAL_REGISTRY_PASSWORD"] %>


env:
  secret:
    - RAILS_MASTER_KEY
    - DATABASE_URL
  clear:
    RAILS_LOG_TO_STDOUT: "1"
    RAILS_SERVE_STATIC_FILES: "1"

ssh:
  user: ubuntu

builder:
  arch: amd64
  remote: ssh://ubuntu@fablecodex.com

accessories:
  postgres:
    image: postgres:16
    host: fablecodex.com
    port: 5432
    env:
      clear:
        POSTGRES_DB: dnd_creator_production
        POSTGRES_USER: dnd_creator
      secret:
        - POSTGRES_PASSWORD
    volumes:
      - /var/lib/dnd-creator-postgres:/var/lib/postgresql/data

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
