service: dnd-creator
image: christianloring/dnd_creator

# Use the IP here so Kamal SSHes to the IP (not the domain)
servers:
  web:
    hosts:
      - 3.18.214.25

proxy:
  ssl: true
  host: fablecodex.com
  # lets_encrypt_email: you@example.com

registry:
  server: ghcr.io
  username: christianloring
  password: <%= ENV["KAMAL_REGISTRY_PASSWORD"] %>

env:
  secret:
    - RAILS_MASTER_KEY
    - DATABASE_URL
  clear:
    RAILS_LOG_TO_STDOUT: "1"
    RAILS_SERVE_STATIC_FILES: "1"

ssh:
  user: ubuntu
  # keys:
  #   - /Users/christianloring/Desktop/website-pair.pem

builder:
  arch: amd64
  remote: ssh://ubuntu@3.18.214.25

# Accessories also SSH to the host — use the IP
accessories:
  postgres:
    image: postgres:16
    host: 3.18.214.25
    port: 5432
    env:
      clear:
        POSTGRES_DB: dnd_creator_production
        POSTGRES_USER: dnd_creator
      secret:
        - POSTGRES_PASSWORD
    volumes:
      - /var/lib/dnd-creator-postgres:/var/lib/postgresql/data

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
